language: objective-c

osx_image: xcode7.3

xcode_sdk: iphonesimulator9.3

script: xcodebuild -workspace Commercetools.xcworkspace -scheme "Commercetools" -destination "platform=iOS Simulator,name=iPhone 6" test

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    tags: true